let  GFX_SCALE = 1
let  GFX_X_OFFSET = 0
let  GFX_Y_OFFSET = 0

let  GFX_FONT_SIZE = 10

let  GFX_BORDER_SIZE = 1

let  GFX_HEADER_SIZE = 34
let  GFX_FOOTER_SIZE = 43

let GFX_WINDOW_WIDTH = 1920
let GFX_WINDOW_HEIGHT = 1080

let SCANNER_WIDTH = 400
let SCANNER_HEIGHT = 240

let GFX_FULLHEADER_SIZE = GFX_HEADER_SIZE + 2 * GFX_BORDER_SIZE
let GFX_FULLFOOTER_SIZE = GFX_FOOTER_SIZE + 2 * GFX_BORDER_SIZE

let GFX_SCANNER_L_COORD = 0
let GFX_SCANNER_R_COORD = (GFX_WINDOW_WIDTH - 1)

let GFX_SCANNER_T_COORD = (GFX_WINDOW_HEIGHT - 1) - SCANNER_HEIGHT + 1
let GFX_SCANNER_B_COORD = GFX_WINDOW_HEIGHT - 1
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// GFX_WINDOW_[xxxxx]
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
let GFX_WINDOW_W_SIZE = GFX_WINDOW_WIDTH
let GFX_WINDOW_H_SIZE = GFX_WINDOW_HEIGHT

let GFX_WINDOW_L_COORD    = 0
let GFX_WINDOW_R_COORD    = GFX_WINDOW_W_SIZE - 1
let GFX_WINDOW_T_COORD    = 0
let GFX_WINDOW_B_COORD    = GFX_WINDOW_H_SIZE - 1
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// GFX_VIEW_[xxxxx]
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

let GFX_VIEW_W_SIZE       = GFX_WINDOW_WIDTH - 2 * GFX_BORDER_SIZE
let GFX_VIEW_H_SIZE       = GFX_WINDOW_HEIGHT - SCANNER_HEIGHT - GFX_FULLFOOTER_SIZE - GFX_FULLHEADER_SIZE

let GFX_VIEW_L_COORD      = GFX_WINDOW_L_COORD + GFX_BORDER_SIZE
let GFX_VIEW_R_COORD      = GFX_WINDOW_R_COORD - GFX_BORDER_SIZE
let GFX_VIEW_T_COORD      = GFX_WINDOW_T_COORD + GFX_FULLHEADER_SIZE
let GFX_VIEW_B_COORD      = GFX_WINDOW_B_COORD - SCANNER_HEIGHT - GFX_FULLFOOTER_SIZE

let GFX_VIEW_X_CENTER     = GFX_VIEW_L_COORD + GFX_VIEW_W_SIZE / 2
let GFX_VIEW_Y_CENTER     = GFX_VIEW_T_COORD + GFX_VIEW_H_SIZE / 2

let GFX_VIEW_KX_SCALE = function(kxx) {
   return  GFX_VIEW_X_CENTER / kxx // 136
}

let GFX_VIEW_KY_SCALE = function(kyy) {
    return GFX_VIEW_Y_CENTER / kyy  // 132
}

let GFX_VIEW_X_SCALE= GFX_VIEW_KX_SCALE(128) // 136
let GFX_VIEW_Y_SCALE= GFX_VIEW_KY_SCALE(48) // 132
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// GFX_FULLVIEW_[xxxxx]
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
let GFX_FULLVIEW_W_SIZE   = GFX_WINDOW_WIDTH - 2 * GFX_BORDER_SIZE
let GFX_FULLVIEW_H_SIZE   = GFX_WINDOW_HEIGHT - SCANNER_HEIGHT - 2 * GFX_BORDER_SIZE

let GFX_FULLVIEW_L_COORD  = GFX_WINDOW_L_COORD
let GFX_FULLVIEW_R_COORD  = GFX_WINDOW_R_COORD
let GFX_FULLVIEW_T_COORD  = GFX_WINDOW_T_COORD
let GFX_FULLVIEW_B_COORD  = GFX_WINDOW_B_COORD - SCANNER_HEIGHT - GFX_BORDER_SIZE

let GFX_FULLVIEW_X_CENTER = GFX_FULLVIEW_L_COORD + GFX_FULLVIEW_W_SIZE / 2
let GFX_FULLVIEW_Y_CENTER = GFX_FULLVIEW_T_COORD + GFX_FULLVIEW_H_SIZE / 2

let GFX_FULLVIEW_KX_SCALE = function(kxx) {
    return GFX_FULLVIEW_X_CENTER / kxx // 136
}

let GFX_FULLVIEW_KY_SCALE = function(kyy) {
    return GFX_FULLVIEW_Y_CENTER / kyy // 132
}

let GFX_FULLVIEW_X_SCALE  = GFX_FULLVIEW_KX_SCALE(128) // 136 256
let GFX_FULLVIEW_Y_SCALE  = GFX_FULLVIEW_KY_SCALE(48) // 132 192
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// let GFX_VIEW_WSIZE		  = GFX_WINDOW_WIDTH - 2 * GFX_BORDER_SIZE
// let GFX_VIEW_HSIZE		  = GFX_WINDOW_HEIGHT - SCANNER_HEIGHT - GFX_FULLFOOTER_SIZE - GFX_FULLHEADER_SIZE
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// GFX_FULLVIEW_[xxxxx]
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
let GFX_X_CENTER		  = GFX_FULLVIEW_X_CENTER
let GFX_Y_CENTER		  = GFX_FULLVIEW_Y_CENTER

let GFX_FOOTER_LSIZE      = GFX_BORDER_SIZE + 16

let GFX_FOOTER_L1         = (GFX_WINDOW_HEIGHT - SCANNER_HEIGHT - GFX_BORDER_SIZE - GFX_FOOTER_SIZE) + 10
let GFX_FOOTER_L2         = (GFX_WINDOW_HEIGHT - SCANNER_HEIGHT - GFX_BORDER_SIZE - GFX_FOOTER_SIZE) + 24

let GFX_VIEW_TX           = GFX_FULLVIEW_L_COORD
let GFX_VIEW_TY           = GFX_FULLVIEW_T_COORD
let GFX_VIEW_BX		   = GFX_FULLVIEW_R_COORD
let GFX_VIEW_BY		   = GFX_FULLVIEW_B_COORD

let GFX_COL_BLACK		= 0
let GFX_COL_DARK_RED	= 28
let GFX_COL_WHITE		= 255
let GFX_COL_GOLD		= 39
let GFX_COL_RED		= 49
let GFX_COL_CYAN		= 11

let GFX_COL_GREY_1		= 248
let GFX_COL_GREY_2		= 235
let GFX_COL_GREY_3		= 234
let GFX_COL_GREY_4		= 237

let GFX_COL_BLUE_1		= 45
let GFX_COL_BLUE_2		= 46
let GFX_COL_BLUE_3		= 133
let GFX_COL_BLUE_4		= 4

let GFX_COL_RED_3		= 1
let GFX_COL_RED_4		= 71

let GFX_COL_WHITE_2		= 242

let GFX_COL_YELLOW_1	= 37
let GFX_COL_YELLOW_2	= 39
let GFX_COL_YELLOW_3	= 89
let GFX_COL_YELLOW_4	= 160
let GFX_COL_YELLOW_5	= 251

let GFX_ORANGE_1		= 76
let GFX_ORANGE_2		= 77
let GFX_ORANGE_3		= 122

let GFX_COL_GREEN_1		= 2
let GFX_COL_GREEN_2		= 17
let GFX_COL_GREEN_3		= 86

let GFX_COL_PINK_1		= 183

let IMG_THE_SCANNER		= 0
let IMG_GREEN_DOT		= 1
let IMG_RED_DOT		= 2
let IMG_BIG_S		= 3
let IMG_ELITE_TXT		= 4
let IMG_BIG_E		= 5
let IMG_DICE		= 6
let IMG_MISSILE_GREEN	= 7
let IMG_MISSILE_YELLOW	= 8
let IMG_MISSILE_RED		= 9
let IMG_BLAKE		= 10
let IMG_NUM_OF		= 11

let PIXEL_FORMAT = "SDL_PIXELFORMAT_ARGB8888"


export const elite = {
    GFX_SCALE: GFX_SCALE,
    GFX_X_OFFSET: GFX_X_OFFSET,
    GFX_Y_OFFSET: GFX_Y_OFFSET,
    GFX_FONT_SIZE: GFX_FONT_SIZE,
    GFX_BORDER_SIZE: GFX_BORDER_SIZE,
    GFX_HEADER_SIZE: GFX_HEADER_SIZE,
    GFX_FOOTER_SIZE: GFX_FOOTER_SIZE,
    GFX_WINDOW_WIDTH: GFX_WINDOW_WIDTH,
    GFX_WINDOW_HEIGHT: GFX_WINDOW_HEIGHT,
    SCANNER_WIDTH: SCANNER_WIDTH,
    SCANNER_HEIGHT: SCANNER_HEIGHT,
    GFX_FULLHEADER_SIZE: GFX_FULLHEADER_SIZE,
    GFX_FULLFOOTER_SIZE: GFX_FULLFOOTER_SIZE,
    GFX_SCANNER_L_COORD: GFX_SCANNER_L_COORD,
    GFX_SCANNER_R_COORD: GFX_SCANNER_R_COORD,
    GFX_SCANNER_T_COORD: GFX_SCANNER_T_COORD,
    GFX_SCANNER_B_COORD: GFX_SCANNER_B_COORD,
    GFX_WINDOW_W_SIZE: GFX_WINDOW_W_SIZE,
    GFX_WINDOW_H_SIZE: GFX_WINDOW_H_SIZE,
    GFX_WINDOW_L_COORD: GFX_WINDOW_L_COORD,
    GFX_WINDOW_R_COORD: GFX_WINDOW_R_COORD,
    GFX_WINDOW_T_COORD: GFX_WINDOW_T_COORD,
    GFX_WINDOW_B_COORD: GFX_WINDOW_B_COORD,
    GFX_VIEW_W_SIZE: GFX_VIEW_W_SIZE,
    GFX_VIEW_H_SIZE: GFX_VIEW_H_SIZE,
    GFX_VIEW_L_COORD: GFX_VIEW_L_COORD,
    GFX_VIEW_R_COORD: GFX_VIEW_R_COORD,
    GFX_VIEW_T_COORD: GFX_VIEW_T_COORD,
    GFX_VIEW_B_COORD: GFX_VIEW_B_COORD,
    GFX_VIEW_X_CENTER: GFX_VIEW_X_CENTER,
    GFX_VIEW_Y_CENTER: GFX_VIEW_Y_CENTER,
    GFX_VIEW_KX_SCALE: GFX_VIEW_KX_SCALE,
    GFX_VIEW_KY_SCALE: GFX_VIEW_KY_SCALE,
    GFX_VIEW_X_SCALE: GFX_VIEW_X_SCALE,
    GFX_VIEW_Y_SCALE: GFX_VIEW_Y_SCALE,
    GFX_FULLVIEW_W_SIZE: GFX_FULLVIEW_W_SIZE,
    GFX_FULLVIEW_H_SIZE: GFX_FULLVIEW_H_SIZE,
    GFX_FULLVIEW_L_COORD: GFX_FULLVIEW_L_COORD,
    GFX_FULLVIEW_R_COORD: GFX_FULLVIEW_R_COORD,
    GFX_FULLVIEW_T_COORD: GFX_FULLVIEW_T_COORD,
    GFX_FULLVIEW_B_COORD: GFX_FULLVIEW_B_COORD,
    GFX_FULLVIEW_X_CENTER: GFX_FULLVIEW_X_CENTER,
    GFX_FULLVIEW_Y_CENTER: GFX_FULLVIEW_Y_CENTER,
    GFX_FULLVIEW_KX_SCALE: GFX_FULLVIEW_KX_SCALE,
    GFX_FULLVIEW_KY_SCALE: GFX_FULLVIEW_KY_SCALE,
    GFX_FULLVIEW_X_SCALE: GFX_FULLVIEW_X_SCALE,
    GFX_FULLVIEW_Y_SCALE: GFX_FULLVIEW_Y_SCALE,
    GFX_X_CENTER: GFX_X_CENTER,
    GFX_Y_CENTER: GFX_Y_CENTER,
    GFX_FOOTER_LSIZE: GFX_FOOTER_LSIZE,
    GFX_FOOTER_L1: GFX_FOOTER_L1,
    GFX_FOOTER_L2: GFX_FOOTER_L2,
    GFX_VIEW_TX: GFX_VIEW_TX,
    GFX_VIEW_TY: GFX_VIEW_TY,
    GFX_VIEW_BX: GFX_VIEW_BX,
    GFX_VIEW_BY: GFX_VIEW_BY,
    GFX_COL_BLACK: GFX_COL_BLACK,
    GFX_COL_DARK_RED: GFX_COL_DARK_RED,
    GFX_COL_WHITE: GFX_COL_WHITE,
    GFX_COL_GOLD: GFX_COL_GOLD,
    GFX_COL_RED: GFX_COL_RED,
    GFX_COL_CYAN: GFX_COL_CYAN,
    GFX_COL_GREY_1: GFX_COL_GREY_1,
    GFX_COL_GREY_2: GFX_COL_GREY_2,
    GFX_COL_GREY_3: GFX_COL_GREY_3,
    GFX_COL_GREY_4: GFX_COL_GREY_4,
    GFX_COL_BLUE_1: GFX_COL_BLUE_1,
    GFX_COL_BLUE_2: GFX_COL_BLUE_2,
    GFX_COL_BLUE_3: GFX_COL_BLUE_3,
    GFX_COL_BLUE_4: GFX_COL_BLUE_4,
    GFX_COL_RED_3: GFX_COL_RED_3,
    GFX_COL_RED_4: GFX_COL_RED_4,
    GFX_COL_WHITE_2: GFX_COL_WHITE_2,
    GFX_COL_YELLOW_1: GFX_COL_YELLOW_1,
    GFX_COL_YELLOW_2: GFX_COL_YELLOW_2,
    GFX_COL_YELLOW_3: GFX_COL_YELLOW_3,
    GFX_COL_YELLOW_4: GFX_COL_YELLOW_4,
    GFX_COL_YELLOW_5: GFX_COL_YELLOW_5,
    GFX_ORANGE_1: GFX_ORANGE_1,
    GFX_ORANGE_2: GFX_ORANGE_2,
    GFX_ORANGE_3: GFX_ORANGE_3,
    GFX_COL_GREEN_1: GFX_COL_GREEN_1,
    GFX_COL_GREEN_2: GFX_COL_GREEN_2,
    GFX_COL_GREEN_3: GFX_COL_GREEN_3,
    GFX_COL_PINK_1: GFX_COL_PINK_1,
    IMG_THE_SCANNER: IMG_THE_SCANNER,
    IMG_GREEN_DOT: IMG_GREEN_DOT,
    IMG_RED_DOT: IMG_RED_DOT,
    IMG_BIG_S: IMG_BIG_S,
    IMG_ELITE_TXT: IMG_ELITE_TXT,
    IMG_BIG_E: IMG_BIG_E,
    IMG_DICE: IMG_DICE,
    IMG_MISSILE_GREEN: IMG_MISSILE_GREEN,
    IMG_MISSILE_YELLOW: IMG_MISSILE_YELLOW,
    IMG_MISSILE_RED: IMG_MISSILE_RED,
    IMG_BLAKE: IMG_BLAKE,
    IMG_NUM_OF: IMG_NUM_OF,
    PIXEL_FORMAT: PIXEL_FORMAT
}