import 'reflect-metadata';
export * from './sidebar';
import { Sidebar } from './sidebar';
import { connect } from './../../../this/react';
import { SidebarService } from './../../../this/services';
import { container } from 'tsyringe';
import { SidebarController } from './../../../this/controller/sidebar';
const sidebarService = container.resolve(SidebarService);
const sidebarController = container.resolve(SidebarController);
export const SidebarView = connect(sidebarService, Sidebar, sidebarController);
