import 'reflect-metadata';
import { container } from 'tsyringe';
import { connect } from './../../../this/react';
import { StatusBar } from './statusBar';
import { StatusBarService } from './../../../this/services';
import { StatusBarController } from './../../../this/controller/statusBar';
export * from './statusBar';
export * from './item';
const statusBarService = container.resolve(StatusBarService);
const statusBarController = container.resolve(StatusBarController);
export const StatusBarView = connect(statusBarService, StatusBar, statusBarController);
