import { Component } from './base-nk/index.mjs';
import obApp from './ob-app/index.mjs'
import obLink from './ob-link/index.mjs'
import nkSqlite from './nk-sqlite/index.mjs'
import nkConcept from './nk-concept/index.mjs'
import nkPing from './nk-ping/index.mjs'
import nkPeer from './nk-peer/index.mjs'
import nkSwagger from './nk-swagger/index.mjs'
import nkMocha from './nk-mocha/index.mjs'
import nkSettings from './nk-settings/index.mjs'
import mssSettings from './mss-settings/index.mjs'
import ferSelect from './fer-select/index.mjs'
import mssInput from './mss-input/index.mjs'
import nkSelf from './nk-self/index.mjs'
import nkMemory from './nk-memory/index.mjs'
import nkBank from './nk-bank/index.mjs'
import nkOpfs from './nk-opfs/index.mjs'
import nkParagraph from './nk-paragraph/index.mjs'
import nkTerminal from './nk-terminal/index.mjs'
import nkSwitch from './nk-switch/index.mjs'
import nkCheckbox from './nk-checkbox/index.mjs'
import nkAudio from './nk-audio/index.mjs'
import nkChart from './nk-chart/index.mjs'
import nkRadio from './nk-radio/index.mjs'
import nkEmulator from './nk-emulator/index.mjs'
import nkOsc from './nk-osc/index.mjs'
import nkTimeLine from './nk-time-line/index.mjs'
import nkFilter from './nk-filter/index.mjs'
import nkInfo from './nk-info/index.mjs'
import nkViews from './nk-views/index.mjs'
import nkTransformers from './nk-transformers/index.mjs'
import nkRotation from './nk-rotation/index.mjs'
import nkSber from './nk-bank/index.mjs'
import nkElite from './nk-elite/index.mjs'
import nkSharedProtocol from './nk-shared-protocol/index.mjs'
import nkGit from './nk-git/index.mjs'
import nkIde from './nk-ide/index.mjs'

export {Component}
export default {
    description: "components"
}