import 'reflect-metadata';
import { connect } from './../../../this/react';
import { ActivityBarController } from './../../../this/controller';
import ActivityBar from './activityBar';
import { container } from 'tsyringe';
import { ActivityBarService } from './../../../this/services';
export * from './activityBar';
export { ActivityBarItem } from './activityBarItem';
const activityBarService = container.resolve(ActivityBarService);
const activityBarController = container.resolve(ActivityBarController);
export const ActivityBarView = connect(activityBarService, ActivityBar, activityBarController);
